### ISSUE TITLE
fine tuning 

### ISSUE THREAD

**Issue by omiderfanmanesh** [ZainNasrullah/music-artist-classification-crnn#9]
I need the weights of the model for fine-tuning my own model and can you please upload the weights of the model on your github page.
thank you in advance

**Comment by ZainNasrullah** [comment]
Hi @omiderfanmanesh; sadly I don't have the weights anymore but by following the instructions contained within the repo, you should be able to replicate all experiments. 

You can request the Artist20 dataset here: https://www.labrosa.org/projects/artistid/

As a reminder, since various audio lengths and dataset splits are investigated in the paper, each one of these experiments yields a different set of model weights.
